Traceback (most recent call last):
  File "C:\Users\Eliana Gomez\anaconda3\envs\WIND\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\Eliana Gomez\anaconda3\envs\WIND\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Eliana Gomez\anaconda3\envs\WIND\lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\Eliana Gomez\anaconda3\envs\WIND\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\Eliana Gomez\anaconda3\envs\WIND\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Eliana Gomez\anaconda3\envs\WIND\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Eliana Gomez\anaconda3\envs\WIND\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from sklearn.metrics import mean_absolute_error

best_mae = np.inf }
best_order = None
best_mdl = None

pq_rng = range(1,5)
d_rng = range(0,3)

for p in pq_rng:
    for d in d_rng:
        for q in pq_rng:
            try:
                tmp_mdl = ARIMA(train, order=(p,d,q)).fit()
                val_pred = tmp_mdl.forecast(steps=len(val))
                tmp_mae = mean_absolute_error(val, val_pred)
                
                if tmp_mae < best_mae:
                    best_mae = tmp_mae
                    best_order = (p,d,q)
                    best_mdl = tmp_mdl
            except:
                continue
------------------


[1;36m  Cell [1;32mIn[8], line 3[1;36m[0m
[1;33m    best_mae = np.inf }[0m
[1;37m                      ^[0m
[1;31mSyntaxError[0m[1;31m:[0m unmatched '}'


